default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development: 
  <<: *default
  database: trainingpal

test:
  <<: *default
  database: trainingpal_test

production:
  <<: *default
  database: trainingpal